#cloud-config
bootcmd:
- printf "[Resolve]\nDNS=8.8.8.8" > /etc/systemd/resolved.conf
- [systemctl, restart, systemd-resolved]
users:
  - name: root
    ssh_authorized_keys:
    - ${ssh_public_key}
growpart:
    mode: auto
    devices: ["/"]
manage_etc_hosts: localhost
locale: "en_US.UTF-8"
package_update: true
package_upgrade: true
packages:
    - haproxy
runcmd:
- systemctl restart haproxy
- touch /tmp/signal
